# Generated by Django 4.2 on 2025-10-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametrainer', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('level', models.IntegerField(max_length=30)),
                ('birthday', models.IntegerField(max_length=30)),
            ],
        ),
    ]
