# Generated by Django 4.2 on 2025-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='level',
            field=models.IntegerField(),
        ),
    ]
