# Generated by Django 5.2.8 on 2025-11-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_pictures/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_pictures/'),
        ),
    ]
